### ISSUE TITLE
Application crash when moving game with folder not present

### ISSUE THREAD

**Issue by kenXengineering** [DjScribbles/GamePipe#1]
Hey. I get the following [error](https://gist.github.com/chosenken/2563e619ed9a5cb37e35) in the log file when I attempt to move a game when its game directory doesn't exist.  This can happen when a game has been removed from the `common` folder, but the `*.acf` file still exits (This situation can happen if you delete the game from the drive and not via Steam).

In this case, the file `appmanifest_232790.acf` exists in the `steamapps` folder (For the game Broken Age).  However, the `installdir` folder does not exists in the `common` folder (Broken Age).  Might want to check if the game directory actually exists when listing the games in the main screen, and if not give an option to clean up the `*.acf` files.

**Comment by DjScribbles** [comment]
Thanks for the detailed report, and suggestion, I fixed the crash in the most recent push.

I'm going to leave this open until I add a good way of handling this situation.

Instead of a reactionary "Would you like to delete this acf file?" I think I may add a "Cleanup & Repair" tab, which finds orphaned acfs and game directories (directory with no acf), which provides options to repair or delete.

The repair option could also be built to help fix situations where the game content is in a different library than the acf file.

**Comment by My1** [comment]
this is a really good Idea, for example if I would have moved the game already away because storage was short before discovering this tool (actually happened thursday when I moved my OS to SSD) and I am too lazy to search out the ACFs.

**Comment by DjScribbles** [comment]
I'm closing this issue since the actual crash has been resolved forever, I've only left it here as reminder to build the cleanup feature, but I've added issue #20 to capture that work.
