### ISSUE TITLE
When deleting games, delete via Steam instead of directly

### ISSUE THREAD

**Issue by RhapsodySL** [DjScribbles/GamePipe#15]
When deleting a game via GamePipe, the entry still exists within Steam. If an update releases for the game, the game will likely be redownloaded. Even if that's not the case, it's still messy.

**Comment by DjScribbles** [comment]
I don't _think_ the game would be re-downloaded, but it would likely download the full update into the old directory, but who knows.

That said, I think the most prudent solution will be to add a prompt to restart when you close Game Pipe, just as if you had moved the game. As it is now, the wingman program (which GamePipe launches quietly in the background) could cover re-deleting the acf if steam recreates it (once steam closes), just as is done with moved games. I've also got plans to add a cleanup page that should detect the dangling folder left behind to make it easy to delete any new content once the acf is gone.

It may also be wise to add a nagging option (or even an automated Steam restart) to wingman for folks who never shutdown their PC's.

**Comment by DjScribbles** [comment]
This issue is as close to closed as it can be without Steam refreshing the ACF status from the disk before starting an update.

It's worth noting that the primary reason for not using the Steam command line options (which can be used to remove a game) is that this option is only functional for a single game, and there is no direct way to know when it is ready for another deletion. Ultimately, the rare event you describe is probably a fair tradeoff for the ability to wipe multiple games at a time (which you can do in Game Pipe via multi-selecting from the list with ctrl or shift).
