### ISSUE TITLE
Game tiles (logos?) do not match the games

### ISSUE THREAD

**Issue by daemonbarber** [DjScribbles/GamePipe#19]
Updated from 0.17 to 1.0 and game tiles no longer match the games.

![gp_error](https://cloud.githubusercontent.com/assets/17881402/23333888/fea6b258-fb61-11e6-8533-98ca20e8e136.jpg)

**Comment by DjScribbles** [comment]
That's strange, nothing has changed with how I load these images, this could be something wonky with steam's image servers, or possibly an issue with the image cache.

On my machine, they show up fine. If you have a moment could you download 0.17 as a zip and quickly check if the issue is also present there? (indicating an issue with the images coming from Steam)

Edit: Also, just noticed that the App Id game pipe is reporting is correct, so it's not confused there.

**Comment by daemonbarber** [comment]
Looks like it was a mixup from updating maybe? After a reboot it seems to be gone.
