### ISSUE TITLE
Able to see hosted games but not pull them

### ISSUE THREAD

**Issue by DethSturm** [DjScribbles/GamePipe#21]
I was able to see the games on my host computer from my laptop, but I was unable to download over LAN.

**Comment by DjScribbles** [comment]
The host computer needs to have Steam installed and it has to have run once (in order to setup the initial library) before you run Game Pipe.

Once those things are done, you simply need to drag the game from the host to the drive cards along the left side.

If you had any error messages or other issues, please provide them, as there isn't enough information to here to help you. Do note that some games may lock up Game Pipe for some time when you drop the game, you should not close the program if it becomes unresponsive here.

**Comment by DethSturm** [comment]
Both computers have steam and the newest version of Gamepipe installed. As well as both having run steam before. The issue is that it wont do anything when dragging the games to the drive from the host.

**Comment by DjScribbles** [comment]
I'm not seeing any issues with this feature on my PC and laptop, and use it fairly regularly myself. The only explanation that comes to mind without more info is that this is that this could be related to issue #22, are you getting a prompt from windows that Game Pipe is not responding, and choosing to close it? Sometimes it takes up to a minute for the files of a single game to be accounted for, and in the meantime the UI is unresponsive. If this is all it is, it's a known issue, the workaround for which is to just let it sit until it finishes what it's doing, if you have multiple games to transfer, you can select them all at once, incurring a potential very long period of unresponsiveness before all of your selections are transferred.

Otherwise, if you could get me the contents of the log file for the run where this issue is occurring (the logs are located at GamePipe\logs\log.txt,  you only need to copy the relevant date, or you can post a link to the whole file located somewhere online).

**Comment by DethSturm** [comment]
It looks like it was just not responding at that time. It seems to be working now that I just tried it. Thanks.

**Comment by DjScribbles** [comment]
Ok, that's great. Sorry for the delays and confusion, resolving the unresponsiveness is covered in #22, so this can be closed since it's a duplicate.
