### ISSUE TITLE
[Feature Request] Use File Share on NAS as LAN Library

### ISSUE THREAD

**Issue by SebbiUltimate** [DjScribbles/GamePipe#28]
It would be convenient if I have a steam library on my NAS to use it via SMB as LAN Library. You could select via dropdown in the Connect to a host field if it is a Game Pipe Server or a Steam Library Share and type the UNC Path of the share. Additionally it would be nice if advanced features like SMB 3.0 Multichannel and multiple adapters/ connections for SMB 2.0 would be supported.

**Comment by DjScribbles** [comment]
You can achieve this goal by mapping your Nas to a drive letter and adding
it as an atchive to your local libraries. Does that work well for what you
are doing?

**Comment by SebbiUltimate** [comment]
Actually on my gaming PC I have set up the NAS share as a mapped drive and installed games as a steam library to it. But when I use my laptop, I want to quickly swap games before I leave, so usually I copied either via Game Pipe from my gaming PC (which is kinda pointless if it is already on the NAS), or I copy via File Explorer from the NAS mapped drive (But I don't have a GUI and have to search for the .acf files). In Steam I can only move but not copy games to my local HDD. It would be cool if you implemented SMB as additional protocol, as I could transfer directly from my NAS.

**Comment by DjScribbles** [comment]
The problem is game pipe connects to another instance of game pipe for the
lan transfer feature, it avoids supporting any particular networking and
sharing configurations, so this would be a huge departure from how things
work now.

However, you mentioned your gaming PC is connected to the NAS as a steam
library. If you connect your laptop as an archive instead of a library,
game pipe offers the option to copy the games from the archive, which I
think would achieve your goal of grabbing things from the NAS without
booting your desktop, and without removing games from the library your
desktop uses. Game pipe also handles the disappearing NAS drive well, it
shouldn't forget the archive location when it's not there ( it just hides
it).

**Comment by SebbiUltimate** [comment]
Thanks for the tip with the archive, I haven't seen this feature yet.
This works so this feature request is fulfilled.

However, I just wanted to show you that UNC support is doable, so I just changed some code in a few minutes and made a Proof of Concept for you:
[gamepipe_unc_poc.zip](https://github.com/DjScribbles/GamePipe/files/1948856/gamepipe_unc_poc.zip)


You can input a UNC Path starting with \\\\ instead of a Host IP and then click on Refresh. I tried it with a small game, the transfer works. Of course this is not a fully working version, it is dirty code and has some bugs like the progress animation, but the base for this is easy. With some SMB 3.0 Multichannel and scaling support it would work better.

Anyways, the archive button works as well :-)
