### ISSUE TITLE
CamelCase SteamApps

### ISSUE THREAD

**Issue by sirmaxim** [DjScribbles/GamePipe#29]
This is not how steam names the directory as they use all lowercase. Does it matter? On network drives it can. I have a drive mounted with NFS where I wanted to put my library. Steam calls it `steamapps` and game pipe simply can't find it, so it creates `SteamApps` which works because the NFS mount OS is FreeBSD. So now both exist and neither game pipe nor steam like it, creating an issue.

**Comment by DjScribbles** [comment]
As a work-around you could create a symbolic link between the two
directories.

I'll have to look into this a little. I can see where I've hand-typed the
camel case version, so it probably should be changed, however I'll want to
make sure it's not ever the other way around.

On Jul 18, 2018 11:08 PM, "sirmaxim" <notifications@github.com> wrote:

This is not how steam names the directory as they use all lowercase. Does
it matter? On network drives it can. I have a drive mounted with NFS where
I wanted to put my library. Steam calls it steamapps and game pipe simply
can't find it, so it creates SteamApps which works because the NFS mount OS
is FreeBSD. So now both exist and neither game pipe nor steam like it,
creating an issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DjScribbles/GamePipe/issues/29>, or mute the thread

**Comment by DjScribbles** [comment]
Sorry for the long delay on this fix, but it is now fixed with 1.0.3.
