### ISSUE TITLE
FR: Copy Games From SMB Share?

### ISSUE THREAD

**Issue by ghost** [DjScribbles/GamePipe#3]
This is an unusual use-case: I have a server box with a lot of storage running Linux. I access SMB shares on the server using my Windows clients.

I would like to be able to store a local copy of my Steam games inside a SMB share.

There are a few different workarounds possible at the moment, but there's no way to treat network share from a box NOT running Game Pipe as a place where you can copy games to / from. You can only move games into or out of such a share.

I'd love to be able to add a SMB share as a LAN Library.

**Comment by DjScribbles** [comment]
It's not possible to add as a LAN library, as those have to be hosting a game pipe service to accept and write files, but the local libraries accepts any windows path and I do plan to add the ability soon to designate an archive as Copy-In and/or Copy-Out so that instead of moving the game, you would copy it.

If this is what you're looking for, I should be able to work it into the next release early-mid week.

**Comment by ghost** [comment]
That would work perfecty!

**Comment by tehbilly** [comment]
:+1: Would be an extremely useful feature

**Comment by DjScribbles** [comment]
This feature was added in fbdae57a67863f3d884c68af2bddd614afa7a662, and released in 0.1.5:
https://github.com/DjScribbles/GamePipe/releases/tag/0.1.5

Closing this issue.
Edit: Or perhaps the better workflow is to allow @DivinityCycle to close?
