### ISSUE TITLE
Duplicate libraries

### ISSUE THREAD

**Issue by sharkusmanch** [DjScribbles/GamePipe#37]
1. Stop Steam

2. Start GamePipe with only default steam library

![start](https://user-images.githubusercontent.com/9328629/127775934-9816c438-46ed-4f68-9918-d61aacfd789b.PNG)

3. Add two new libraries (E:/games and D:/Games in my case). These libraries already have games and have been added to Steam manually.

![added](https://user-images.githubusercontent.com/9328629/127775940-59ffaddb-8e2c-45bc-8c08-a09a8f4700f7.PNG)

4. Restart GamePipe

![duplicate](https://user-images.githubusercontent.com/9328629/127775969-f0e8983f-73dc-4bb3-9329-4cdc990fec13.PNG)

**Comment by sharkusmanch** [comment]
Attempting to remove the duplicates will result in GamePipe missing E:/games and D:/Games upon restart.

**Comment by DjScribbles** [comment]
When did you add the libraries via steam, was it prior to starting game
pipe?

GP should automatically detect all steam libraries when it starts, so
adding a library that is already in steam is redundant, but it's possible
something changed on steam.

**Comment by sharkusmanch** [comment]
> When did you add the libraries via steam, was it prior to starting game
pipe?

Yes, added them manually before starting GP.

Quickly tested the following:

1. Stopped GP
2. Removed E:/games and D:/Games from Steam libraries
2. Stopped Steam
3. Start GP, now only shows default C:/ library as expected
4. Added E:/games and D:/Games to GP libraries
5. Stop GP
6. Start Steam
6. Start GP, now showing duplicate libraries again

**Comment by DjScribbles** [comment]
Yea, so I checked this out a bit, and Steam has indeed changed the formatting of libraryfolders.vdf, which is where game-pipe picks up all the libraries from. Oddly, my primary hasn't changed yet, but another PC in the house is on the new format.

To resolve this, I've modified the library finder to accept the new format, which was a tiny regex change (it also accepts the old format). I also disabled the Add/Remove Library features, since they're not functional with the new style. Archives can still be added/removed.

You may need to manually edit your "steamapps\Libraryfolders.vdf" and remove the lines that look like below in order to remove the duplication:
![image](https://user-images.githubusercontent.com/2068020/127792388-6e3a7aa6-6e35-4c95-a4e0-c3bf47432c6f.png)
If you'd prefer, feel free to attach your vdf file and I'll manually edit it for you.
